version: '3.1'

services:
  db:
    image: postgres:15.1
    container_name: accesapp
    restart: always
    environment:
      POSTGRES_DB: accesapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432